name: Github Pages Pusher

on:
  workflow_dispatch: 
  pull_request:
    branches: [ master ]
    types: [ synchronize, opened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p ./dest && cp -r ./src/page/* ./dest/ && cp -r ./src/img ./dest/ && sed -i 's/\.\.\/\.\.\/\.\.\/img/\.\/img/g' ./dest/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dest
